// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package correlations

import (
	"database/sql"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/os/gtime"
)

// Entity is the golang structure for table rotab_correlations.
type Entity struct {
    Id        int         `orm:"id"         json:"id"`         //   
    CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` //   
    UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` //   
    DeletedAt *gtime.Time `orm:"deleted_at" json:"deleted_at"` //   
    Id1       int64       `orm:"id1"        json:"id_1"`       //   
    Id2       int64       `orm:"id2"        json:"id_2"`       //   
    Str1      string      `orm:"str1"       json:"str_1"`      //   
    Str2      string      `orm:"str2"       json:"str_2"`      //   
    Str3      string      `orm:"str3"       json:"str_3"`      //   
    Str4      string      `orm:"str4"       json:"str_4"`      //   
    Int1      int         `orm:"int1"       json:"int_1"`      //   
    Int2      int         `orm:"int2"       json:"int_2"`      //   
    Int3      int         `orm:"int3"       json:"int_3"`      //   
    Int4      int         `orm:"int4"       json:"int_4"`      //   
    Type      int         `orm:"type"       json:"type"`       //   
    BlogId    int64       `orm:"blog_id"    json:"blog_id"`    //   
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (r *Entity) OmitEmpty() *arModel {
	return Model.Data(r).OmitEmpty()
}

// Inserts does "INSERT...INTO..." statement for inserting current object into table.
func (r *Entity) Insert() (result sql.Result, err error) {
	return Model.Data(r).Insert()
}

// InsertIgnore does "INSERT IGNORE INTO ..." statement for inserting current object into table.
func (r *Entity) InsertIgnore() (result sql.Result, err error) {
	return Model.Data(r).InsertIgnore()
}

// Replace does "REPLACE...INTO..." statement for inserting current object into table.
// If there's already another same record in the table (it checks using primary key or unique index),
// it deletes it and insert this one.
func (r *Entity) Replace() (result sql.Result, err error) {
	return Model.Data(r).Replace()
}

// Save does "INSERT...INTO..." statement for inserting/updating current object into table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Save() (result sql.Result, err error) {
	return Model.Data(r).Save()
}

// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Update() (result sql.Result, err error) {
	return Model.Data(r).Where(gdb.GetWhereConditionOfStruct(r)).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
func (r *Entity) Delete() (result sql.Result, err error) {
	return Model.Where(gdb.GetWhereConditionOfStruct(r)).Delete()
}